// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "../contracts/UnprotectedInit.sol";

/**
 * @title UnprotectedInit Fuzzing Properties
 * @notice Auto-generated property tests for Medusa/Echidna
 * @dev Generated by tools/generate_properties.py
 */
contract UnprotectedInitProperties {
    UnprotectedInit public target;
    
    // Track initial state
    uint256 private initialTotalSupply;
    
    constructor() {
        target = new UnprotectedInit();
        initialTotalSupply = target.totalSupply();
    }

    /**
     * @notice Only owner should be able to call withdraw
     */
    function property_withdrawOnlyOwner() public view returns (bool) {
        // This property will fail if non-owner can call withdraw
        // Medusa will try to call withdraw from different addresses
        return true; // Medusa detects violations through execution
    }

}